Dyd.BusinessMQ.Web/Areas/DataNode/Controllers/QueuePartitionController.cs
using Dyd.BusinessMQ.Domain;
using Dyd.BusinessMQ.Domain.Dal;
using Dyd.BusinessMQ.Domain.Model;
using Dyd.BusinessMQ.Domain.Model.manage;
using Dyd.BusinessMQ.Web.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using XXF.Db;
using Webdiyer.WebControls.Mvc;
using XXF.ProjectTool;
using XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime;

namespace Dyd.BusinessMQ.Web.Areas.DataNode.Controllers
{
    public class QueuePartitionController : BaseController
    {
        //
        // GET: /ProConsum/QueuePartition/

        private tb_mqpath_partition_dal pathPartitionDal = new tb_mqpath_partition_dal();
        private tb_partition_dal partitionDal = new tb_partition_dal();
        private tb_mqpath_dal mqPathDal = new tb_mqpath_dal();

        public ActionResult Index(string mqpathid, string partitionId, int pageIndex = 1, int pageSize = 30)
        {
            ViewBag.mqpathid = mqpathid; ViewBag.partitionId = partitionId;
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                int count = 0;
                IList<MqPathPartitionModel> list = pathPartitionDal.GetPageList(conn, mqpathid, partitionId, pageIndex, pageSize, ref count);
                var partitionids = list.Select(c => c.mqpath_partition_model.partitionid).ToList();
                Dictionary<int, List<ConsumerPartitionModel>> rs = new Dictionary<int, List<ConsumerPartitionModel>>();
                foreach (var o in new tb_consumer_partition_dal().ListByPartitionIds(conn, partitionids))
                {
                    if (!rs.ContainsKey(o.consumerpartitionmodel.partitionid))
                    {
                        rs.Add(o.consumerpartitionmodel.partitionid, new List<ConsumerPartitionModel>());
                    }
                    rs[o.consumerpartitionmodel.partitionid].Add(o); ;
                }
                ViewBag.consumers = rs;
                PagedList<MqPathPartitionModel> pageList = new PagedList<MqPathPartitionModel>(list, pageIndex, pageSize, count);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("List", pageList);
                }
                ViewBag.ServerDate = conn.GetServerDate();
                return View(pageList);
            }
        }
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(tb_mqpath_partition_model model)
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
                {
                    try
                    {
                        conn.Open();
                        conn.BeginTransaction();
                        model.state = (byte)XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.EnumMqPathPartitionState.Running;
                        model.partitionindex = new tb_mqpath_partition_dal().GetMaxPartitionIndexOfMqPath(conn, model.mqpathid) + 1;
                        if (new tb_mqpath_dal().Get(conn, model.mqpathid) == null)
                        {
                            throw new Exception("无法找到队列");
                        }
                        if (new tb_mqpath_partition_dal().GetByPartitionId(conn, model.partitionid) != null)
                        {
                            throw new Exception("分区已被使用");
                        }
                        if (new tb_mqpath_partition_dal().CheckMaxPartitionIndexOfMqPathIsRunning(conn, model.mqpathid) == false)
                        {
                            throw new Exception("最后的分区未处于正常使用状态,若分区正在待删状态,请删除完毕后新增分区。");
                        }
                        if (new tb_mqpath_partition_dal().Add2(conn, model))
                        {
                            new tb_partition_dal().UpdateIsUsed(conn, 1, model.partitionid);
                            var partitioninfo = XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.PartitionRuleHelper.GetPartitionIDInfo(model.partitionid);
                            //创建3天的表
                            var serverdate = conn.GetServerDate().Date;
                            for (int i = 0; i < 3; i++)
                            {
                                var currentdate = serverdate.AddDays(i);
                                var tablename = XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.PartitionRuleHelper.GetTableName(partitioninfo.TablePartition, currentdate);//
                                SqlHelper.ExcuteSql(DataConfig.DataNodeParConn(partitioninfo.DataNodePartition + ""), (c) =>
                                {
                                    bool exsit = c.TableIsExist(tablename);
                                    if (exsit != true)
                                    {
                                        string cmd = DataConfig.MQCreateTableSql.Replace("{tablepartiton}", XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.PartitionRuleHelper.PartitionNameRule(partitioninfo.TablePartition))
                                            .Replace("{daypartition}", currentdate.ToString("yyMMdd")).Replace("{datanodepartiton}", XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.PartitionRuleHelper.PartitionNameRule(partitioninfo.DataNodePartition));
                                        c.ExecuteSql(cmd, new List<XXF.Db.ProcedureParameter>());
                                    }
                                });
                            }
                            conn.Commit();

                        }
                        else
                            throw new Exception("更新错误");

                    }
                    catch (Exception exp)
                    {
                        conn.Rollback();
                        throw exp;
                    }
                }
                ReStartQuque(model.mqpathid);
                return RedirectToAction("index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError("Error", e.Message);
                return View(model);
            }


        }

        public ActionResult SetState(int partitionid, int state)
        {
            try
            {
                tb_mqpath_partition_model model = null;
                using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
                {
                    conn.Open();
                    model = new tb_mqpath_partition_dal().GetByPartitionId(conn, partitionid);
                    new tb_mqpath_partition_dal().SetState(conn, partitionid, state);
                }
                SendCommandToRedistReStart(model.mqpathid, EnumCommandReceiver.Producter);
                return Json(new { code = 1, msg = "成功" });
            }
            catch (Exception exp)
            {
                return Json(new { code = -1, msg = exp.Message });
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                tb_mqpath_partition_model model = null;
                using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
                {
                    try
                    {
                        conn.Open();
                        conn.BeginTransaction();
                        model = pathPartitionDal.Get(conn, id);
                        if (model == null)
                            throw new Exception("分区不存在");

                        if (model.state == (int)XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.EnumMqPathPartitionState.Running)
                        {
                            throw new Exception("正在运行中");
                        }
                        if (model.partitionindex != new tb_mqpath_partition_dal().GetMaxPartitionIndex(conn, model.mqpathid))
                        {
                            throw new Exception("分区请优先移除最大的分区顺序的分区");
                        }
                        //移除该分区的所有消费者信息
                        new tb_consumer_partition_dal().Delete2(conn, model.partitionid);
                        pathPartitionDal.Delete(conn, id);
                        new tb_partition_dal().UpdateIsUsed(conn, 0, model.partitionid);
                        conn.Commit();

                    }
                    catch (Exception exp)
                    {
                        conn.Rollback();
                        throw exp;
                    }
                }
                ReStartQuque(model.mqpathid);
                return Json(new { code = 1, msg = "成功" });
            }
            catch (Exception e)
            {

                return Json(new { code = -1, msg = e.Message });
            }
        }
        /// <summary>
        /// 获取所有分区节点
        /// </summary>
        /// <returns></returns>
        public JsonResult GetNode()
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                IList<string> list = new tb_datanode_dal().GetNodeList(conn);
                if (list != null && list.Count > 0)
                {
                    return Json(list, JsonRequestBehavior.AllowGet);
                }
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }
        /// <summary>
        /// 获取所有分区节点
        /// </summary>
        /// <returns></returns>
        public JsonResult GetPartition(string datanodeid)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                List<tb_partition_model> list = partitionDal.GetAllCanUsePartitionList(conn,Convert.ToInt32( datanodeid));
                if (list != null && list.Count > 0)
                {
                    return Json(list, JsonRequestBehavior.AllowGet);
                }

Dyd.BusinessMQ.Web/Areas/ProConsum/Controllers/QueueController.cs
using Dyd.BusinessMQ.Domain;
using Dyd.BusinessMQ.Domain.Dal;
using Dyd.BusinessMQ.Domain.Model;
using Dyd.BusinessMQ.Domain.Model.manage;
using Dyd.BusinessMQ.Web.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime;
using XXF.Db;
using Webdiyer.WebControls.Mvc;
using XXF.Extensions;

namespace Dyd.BusinessMQ.Web.Areas.ProConsum.Controllers
{
    public class QueueController : BaseController
    {
        //
        // GET: /DataNode/Queue/

        private tb_mqpath_partition_dal dal = new tb_mqpath_partition_dal();
        private tb_mqpath_dal pathDal = new tb_mqpath_dal();

        public ActionResult Index(string mqpathid = "", string mqpath = "", int pageIndex = 1, int pageSize = 30, int partitionId = 0)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                int count = 0;
                ViewBag.mqpathid = mqpathid; ViewBag.mqpath = mqpath;
                ViewBag.partitionId = partitionId;
                ViewBag.ServerDate = conn.GetServerDate();
                IList<MqPathModel> list = pathDal.GetPageList(conn, mqpathid, mqpath, pageIndex, pageSize, ref count);
                PagedList<MqPathModel> pageList = new PagedList<MqPathModel>(list, pageIndex, pageSize, count);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("List", pageList);
                }
                return View(pageList);
            }
        }
        public ActionResult Update(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                tb_mqpath_model model = pathDal.Get(conn, id);
                return View(model);
            }
        }
        [HttpPost]
        public ActionResult Update(tb_mqpath_model model)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                tb_mqpath_model result = pathDal.Get(conn, model.id);
                if (result != null)
                {
                    result.mqpath = model.mqpath;
                    result.lastupdatetime = DateTime.Now;
                    if (pathDal.Edit(conn, result))
                    {
                        return RedirectToAction("index");
                    }
                }
                ModelState.AddModelError("Error", "更新错误");
                return View(result);
            }
        }
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(string mqpath)
        {
            try
            {
                if (mqpath.isint() == true)
                    throw new Exception("队列名不允许为数字");
                using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
                {
                    conn.Open();
                    if (pathDal.Add2(conn, mqpath.ToLower()))
                    {
                        return RedirectToAction("index");
                    }
                    throw new Exception("添加错误");
                }
            }
            catch (Exception exp)
            {
                ModelState.AddModelError("Error", exp.Message);
                return View(mqpath);
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
                {
                    try
                    {
                        conn.Open();
                        conn.BeginTransaction();
                        var countofpatitions = dal.GetCountOfPartition(conn, id);
                        if (countofpatitions > 0)
                            throw new Exception("请先删除该队列全部分区后删除该队列");
                        new tb_mqpath_dal().Delete(conn, id);
                        conn.Commit();
                        return Json(new { code = 1, msg = "删除成功" });
                    }
                    catch (Exception exp)
                    {
                        conn.Rollback();
                        throw exp;
                    }

                }
            }
            catch (Exception exp)
            {

                return Json(new { code = -1, msg = exp.Message });
            }
        }



        public ActionResult ReStart(int id)
        {
            try
            {
                ReStartQuque(id);
                return Json(new { code = 1, msg = "已通知消费者和生产者更新" });

            }
            catch (Exception exp)
            {

                return Json(new { code = -1, msg = exp.Message });
            }
        }
    }
}

Dyd.BusinessMQ.Web/Areas/DataNode/Views/QueuePartition/Add.cshtml
@{
    ViewBag.Title = "新增";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Dyd.BusinessMQ.Domain.Model.tb_mqpath_partition_model

<script type="text/javascript">
    $(document).ready(function () {
        getMqPath();
        getNode();
        getPartition();
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#datanodeid").change(function () {
            getPartition();
        });
    });
    function getPartition() {
        $.ajax({
            url: '/DataNode/QueuePartition/GetPartition',
            type: 'get',
            data: {
                datanodeid: $("#datanodeid").val()
            },
            success: function (data) {
                $("#partitionid").html("");
                if (data) {
                    for (var i = 0; i < data.length; i++) {
                        $("#partitionid").append("<option value=\"" + data[i].partitionid + "\">" + data[i].partitionid + "</option>");
                    }
                }
            },
            async: false,
            error: function () {
                alert("你的网络出小差了，请重试。");
            }
        });
    }
    function getNode() {
        $.ajax({
            url: '/DataNode/QueuePartition/GetNode',
            type: 'get',
           
            async: false,
            success: function (data) {
                $("#datanodeid").html("");
                if (data) {
                    for (var i = 0; i < data.length; i++) {
                        $("#datanodeid").append("<option value=\"" + data[i] + "\">" + data[i] + "</option>");
                    }
                }
            },
            error: function () {
                alert("你的网络出小差了，请重试。");
            }
        });
    }
    function getMqPath() {
        $.ajax({
            url: '/DataNode/QueuePartition/GetMqPath',
            type: 'get',
            success: function (data) {
                $("#mqpathid").html("");
                if (data) {
                    for (var i = 0; i < data.length; i++) {
                        $("#mqpathid").append("<option value=\"" + data[i].key + "\">" + data[i].value + "</option>");
                    }
                }
            },
            error: function () {
                alert("你的网络出小差了，请重试。");
            }
        });
    }

</script>
<div class="head">
    <div class="title">
        新增
    </div>
</div>
<div>
    @using (Html.BeginForm("Add", "QueuePartition", FormMethod.Post, new { enctype = "multipart/form-data", @onsubmit = "return sub()" }))
    {
        <ul class="mydetail">
            
             <li><label>所有节点</label><select id="datanodeid" name="datanodeid">
                </select></li>
            <li><label>可用分区</label><select id="partitionid" name="partitionid">
                </select></li>
            <li><label>队列</label><select id="mqpathid" name="mqpathid">
                </select></li>
            @*<li>
                <label>状态</label><select id="state" name="state">
                  <option value="1">运行中</option>
                  <option value="100">等待消费</option>
                </select>
            </li>
             <li>
                <label>顺序号</label>
                 <input  type="text" id="partitionindex" name="partitionindex"/>
            </li>*@
            <li>
                <input type="submit" class="btn1" value="提交" />@Html.ValidationMessage("Error")
            </li>
        </ul>
    }
</div>

Dyd.BusinessMQ.Web/Areas/DataNode/Views/QueuePartition/Index.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BusinessMQ.Domain.Model.manage.MqPathPartitionModel>
@{
    ViewBag.Title = "队列分区管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    function Delete(id) {
        if (confirm("移除分区后,需要确认等待一段时间,确认该分区的消费者已将分区剩余的消息消费完毕再进行删除操作,否则会造成该分区消费信息丢失,确认要删除分区吗？")) {
            $.ajax({
                url: '@Url.Action("Delete","QueuePartition")',
                type: "post",
                data: {
                    id: id
                },
                success: function (data) {
                    if (data.code > 0) {
                        alert("成功！");
                        window.location = window.location;
                    }
                    else {
                        alert(data.msg); 
                    }
                }
            })
        }
    }
    function SetState(partitionid, state) {
        if (confirm("确定设置分区为待移除状态吗？")) {//
                $.ajax({
                    url: '@Url.Action("SetState","QueuePartition")',
                    type: "post",
                    data: {
                        partitionid: partitionid, state: state
                    },
                    success: function (data) {
                        if (data.code > 0) {
                            alert("成功！");
                            window.location = window.location;
                        }
                        else {
                            alert(data.msg);
                        }
                    }
                })
            }
    }
</script>
@section Scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    @{Html.RegisterMvcPagerScriptResource();}
}
<div class="head">
    <div class="title">
        队列分区管理  @Html.Raw(Dyd.BusinessMQ.Web.Base.CommonHelper.Help(@"队列的分区管理,用于队列的分区分配及删除操作;注意：
队列添加分区按照分区顺序添加，队列删除分区按照分区顺序删除;
一个分区只能分配个一个队列,一个队列可以有多个分区,删除分区前要先移除分区,并在确认分区消息全部消费完毕后移除分区;
否则会导致被移除的分区部分消息不被消费;当然也可手工从数据库迁移被移除的消息至未移除的分区;对队列分区的操作将会通知队列更新,从而通知消费者端和生产者获取最新的分区队列。"))
    </div>
</div>
<div class="orderlist m10 myorder">
    @using (Html.BeginForm("index", "QueuePartition", FormMethod.Get, new RouteValueDictionary { { "id", "searchForm" } }))
    {
        <div class="item_list pt10">
            <div class="item_list">
                <ul>
                    <li>
                        <label>队列</label>
                        <input type="text" style="width:150px" name="mqpathid" value="@ViewBag.mqpathid" />
                        <label>分区编号</label>
                        <input type="text" style="width:150px" name="partitionId" value="@ViewBag.partitionId" />
                    </li>
                    <li class="search">
                        <input type="submit" class="btn1" value="搜索" accesskey="S" /></li>
                </ul>
            </div>
        </div>
    }
    <a href="@Url.Action("add", "QueuePartition")" class="btn1">新增</a>
    <div class="tab_cont">
        <div class="List">
            @Html.Partial("List",Model)
        </div>
    </div>
</div>

Dyd.BusinessMQ.Web/Areas/DataNode/Views/QueuePartition/List.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BusinessMQ.Domain.Model.manage.MqPathPartitionModel>

<style>


        .divhide {
        overflow:hidden;
        height:200px;
        }
    .divopen {
    }
</style>
<table>
    <tbody><tr>
         <th style="width:200px;">队列[ID]</th>
         <th style="width:60px;">分区序号</th>
         <th style="width:60px;">分区编号</th>
         <th style="width:60px;">状态</th>
        <th style="width:120px;">创建时间</th>
        <th style="">相关消费者</th>
        <th>操作</th>
    </tr>
        @foreach (var item in Model)
        {
           <tr style=" ">
            <td style="text-align:left;"><a target="_blank" href="@Url.Action("Index", "Queue", new { Area="ProConsum",mqpathid=item.mqpath_partition_model.mqpathid })">@item.mqpath [@item.mqpath_partition_model.mqpathid]</a></td>
               <td style="text-align:left;">@item.mqpath_partition_model.partitionindex</td>
             <td style="text-align:left;">@item.mqpath_partition_model.partitionid</td>
               <td style="text-align:left;">@(Dyd.BusinessMQ.Core.EnumUtils<XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.EnumMqPathPartitionState>.GetText((XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.EnumMqPathPartitionState)item.mqpath_partition_model.state))</td>
               <td style="text-align:left;">@Dyd.BusinessMQ.Core.CommonHelper.ShowTime(ViewBag.ServerDate,item.mqpath_partition_model.createtime)</td>

            <td style="text-align:left; vertical-align:top;">
                @if(ViewBag.consumers !=null)
                {
                    var cs = ViewBag.consumers as Dictionary<int, List<Dyd.BusinessMQ.Domain.Model.manage.ConsumerPartitionModel>>;
                    if (cs.ContainsKey(item.mqpath_partition_model.partitionid))
                    {
                        foreach (var o in cs[item.mqpath_partition_model.partitionid])
                        { <p><a target="_blank" href="@Url.Action("Index", "Consumer", new { Area="ProConsum",consumerclientid=o.consumerpartitionmodel.consumerclientid,partitionid=item.mqpath_partition_model.partitionid })">@o.client (@o.nonMsgCount)未消费/(@o.msgCount)已消费</a></p>} 
                    }
                    
                }
            </td>
            <td>
                @if (item.mqpath_partition_model.partitionindex == item.maxpartitionindex)
                { 
                    if (item.mqpath_partition_model.state == (byte)XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.EnumMqPathPartitionState.Running)
                    {<input type="button" value="准备移除" onclick="SetState('@item.mqpath_partition_model.partitionid',@((byte)XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.EnumMqPathPartitionState.WaitConsumeCompleted))">}
                    else
                    {
                        <input type="button" value="设置可用" onclick="SetState('@item.mqpath_partition_model.partitionid    ',@((byte)XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.EnumMqPathPartitionState.Running))">
                        <input type="button" value="删除" onclick="    Delete('@item.mqpath_partition_model.id    ')">
                    }
                }
            </td>
        </tr>
        }
</tbody></table>
<div class="total pt10">
    <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
    @Html.Pager(Model, new PagerOptions { PageIndexParameterName = "pageIndex", ShowPageIndexBox = true, PageIndexBoxType = PageIndexBoxType.TextBox, CssClass = "mvcPager" })
    @*@Ajax.Pager(Model, new PagerOptions { PageIndexParameterName = "pageindex", ShowPageIndexBox = true, PageIndexBoxType = PageIndexBoxType.DropDownList, ShowGoButton = false }, new MvcAjaxOptions { UpdateTargetId = "List", HttpMethod = "Post", DataFormId = "searchForm" }, new { @class = "pager_page" })*@
</div>