Dyd.BusinessMQ.Web/Areas/DataNode/Controllers/NodeController.cs
using Dyd.BusinessMQ.Domain;
using Dyd.BusinessMQ.Domain.Dal;
using Dyd.BusinessMQ.Domain.Model;
using Dyd.BusinessMQ.Web.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XXF.Db;
using Webdiyer.WebControls.Mvc;

namespace Dyd.BusinessMQ.Web.Areas.DataNode.Controllers
{
    public class NodeController : BaseController
    {
        private tb_datanode_dal nodeDal = new tb_datanode_dal();
        private tb_partition_dal partitionDal = new tb_partition_dal();
        private int pageSize = 30;
        //
        // GET: /DataNode/Node/

        public ActionResult Index(int pageIndex = 1)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                int count = 0;
                IList<tb_datanode_model> list = nodeDal.GetPageList(conn, pageIndex, pageSize, ref count);
                PagedList<tb_datanode_model> pageList = new PagedList<tb_datanode_model>(list, pageIndex, pageSize, count);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("List", pageList);
                }
               
                return View(pageList);
            }
        }
        public ActionResult Delete(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                var model = new tb_datanode_dal().Get(conn,id);
                bool isExistPartion = partitionDal.IsExistPartition(conn, model.datanodepartition);
                if (isExistPartion)
                {
                    return Json(new { code = -1, msg = "该节点存在分区，请先删除分区，再进行删除节点操作" });
                }
                else
                {
                    bool flag = nodeDal.Delete(conn, id);
                    if (flag)
                    {
                        return Json(new { code = 1, msg = "删除成功" });
                    }
                    return Json(new { code = -1, msg = "删除失败" });
                }
            }
        }
        [HttpPost]
        public ActionResult Update(tb_datanode_model model)
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
                {
                    conn.Open();
                    if (model.datanodepartition < 1 || model.datanodepartition >= 100)
                    {
                        throw new Exception("节点编号只允许1~99之间");
                    }
                    if (nodeDal.IsExist(conn, model.id, model.datanodepartition))
                    {
                        throw new Exception("节点编号已存在");
                    }
                    if (nodeDal.Edit(conn, model) == false)
                    {
                        throw new Exception("更新错误");
                    }
                }
                return RedirectToAction("index");
            }
            catch (Exception exp)
            {
                ModelState.AddModelError("Error", exp.Message);
                return View(model);
            }
        }
        public ActionResult Update(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                tb_datanode_model model = nodeDal.Get(conn, id);
                return View(model);
            }
        }
        public ActionResult Add()
        {
            IList<string> usednodes = new List<string>();
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                usednodes = new tb_datanode_dal().GetNodeList(conn);
            }
            List<string> unUsednodes = new List<string>();
            for (var i = 1; i < 100; i++)
            {
                var nodeid = XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.PartitionRuleHelper.PartitionNameRule(i);
                //var partition = XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.PartitionRuleHelper.GetPartitionID(new XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.PartitionIDInfo() { DataNodePartition = nodeid, TablePartition = i });
                if (!usednodes.Contains(nodeid))
                    unUsednodes.Add(nodeid);
            }
            ViewBag.unusednodes = unUsednodes;
            return View();
        }
        [HttpPost]
        public ActionResult Add(tb_datanode_model model)
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
                {
                    conn.Open();
                    if (model.datanodepartition < 1 || model.datanodepartition >= 100)
                    {
                        throw new Exception("节点编号只允许1~99之间");
                    }
                    if (nodeDal.IsExist(conn, model.id, model.datanodepartition))
                    {
                        throw new Exception("节点编号已存在");
                    }
                    if (nodeDal.Add(conn, model) == false)
                    {
                        throw new Exception("更新错误");
                    }
                }
                return RedirectToAction("index");
            }
            catch (Exception exp)
            {
                ModelState.AddModelError("Error", exp.Message);
                return View(model);
            }
        }
    }
}

Dyd.BusinessMQ.Web/Areas/Log/Controllers/LogController.cs
using Dyd.BusinessMQ.Domain;
using Dyd.BusinessMQ.Domain.Dal;
using Dyd.BusinessMQ.Domain.Model;
using Dyd.BusinessMQ.Web.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XXF.Db;
using Webdiyer.WebControls.Mvc;

namespace Dyd.BusinessMQ.Web.Areas.Log.Controllers
{
    public class LogController : BaseController
    {
        private tb_log_dal logDal = new tb_log_dal();
        private tb_debuglog_dal debugDal = new tb_debuglog_dal();
        private tb_error_dal errorDal = new tb_error_dal();
        //
        // GET: /Log/Error/
        public ActionResult LogIndex(DateTime? startTime, DateTime? endTime, string mqpathid, string methodname, string info, int pageIndex = 1, int pageSize = 30)
        {
            int count = 0;
            string mqpath = "";
            GetQueryInfo(ref startTime, ref endTime, mqpathid, mqpath, methodname, info);
            using (DbConn conn = DbConfig.CreateConn(DataConfig.LogConn))
            {
                conn.Open();
                IList<tb_log_model> list = logDal.GetPageList(conn, startTime, endTime, mqpathid, mqpath, methodname, info, pageSize, pageIndex, ref count);
                PagedList<tb_log_model> pageList = new PagedList<tb_log_model>(list, pageIndex, pageSize, count);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("LogList", pageList);
                }
                return View(pageList);
            }
        }
        /// <summary>
        /// DebugLog
        /// </summary>
        /// <param name="startTime"></param>
        /// <param name="endTime"></param>
        /// <param name="pageIndex"></param>
        /// <param name="pageSize"></param>
        /// <returns></returns>
        public ActionResult DebugIndex(DateTime? startTime, DateTime? endTime, string mqpathid, string methodname, string info, int pageIndex = 1, int pageSize = 30)
        {
            int count = 0; string mqpath = "";
            GetQueryInfo(ref startTime,ref endTime, mqpathid,mqpath, methodname, info);
            using (DbConn conn = DbConfig.CreateConn(DataConfig.LogConn))
            {
                conn.Open();
                IList<tb_debuglog_model> list = debugDal.GetPageList(conn, startTime, endTime, mqpathid, mqpath, methodname,info, pageSize, pageIndex, ref count);
                PagedList<tb_debuglog_model> pageList = new PagedList<tb_debuglog_model>(list, pageIndex, pageSize, count);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("DebugList", pageList);
                }
                return View(pageList);
            }
        }

        public ActionResult ErrorIndex(DateTime? startTime, DateTime? endTime, string mqpathid, string methodname, string info, int pageIndex = 1, int pageSize = 30)
        {
            int count = 0;
            string mqpath = "";
            GetQueryInfo(ref startTime, ref endTime, mqpathid, mqpath, methodname, info);
            using (DbConn conn = DbConfig.CreateConn(DataConfig.LogConn))
            {
                conn.Open();
                IList<tb_error_model> list = errorDal.GetPageList(conn, startTime, endTime, mqpathid, mqpath, methodname, info, pageSize, pageIndex, ref count);
                PagedList<tb_error_model> pageList = new PagedList<tb_error_model>(list, pageIndex, pageSize, count);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("ErrorList", pageList);
                }
                return View(pageList);
            }
        }

        private void GetQueryInfo(ref DateTime? startTime, ref DateTime? endTime, string mqpathid, string mqpath, string methodname, string info)
        {
            mqpath = "";
            if (startTime != null)
            {
                startTime = startTime.Value;
            }
            else
            {
                startTime = DateTime.Now.AddDays(-30);
            }
            if (endTime != null)
            {
                endTime = endTime.Value;
            }
            else
            {
                endTime = DateTime.Now.AddDays(1);
            }
            if (!string.IsNullOrEmpty(mqpathid))
            {
                int mqpathidint = 0;
                if (int.TryParse(mqpathid, out mqpathidint) == true)
                { mqpathid = mqpathidint + ""; }
                else
                { mqpath = mqpathid; }
            }
            ViewBag.startTime = startTime; ViewBag.endTime = endTime; ViewBag.mqpathid = mqpathid + mqpath; ViewBag.methodname = methodname; ViewBag.info = info;
        }

        public ActionResult DebugDeleteAll()
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.LogConn))
            {
                conn.Open();
                debugDal.DeleteAll(conn);
                return Json(new { code = 1, msg = "删除成功" });
            }
        }
        public ActionResult ErrorDeleteAll()
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.LogConn))
            {
                conn.Open();
                errorDal.DeleteAll(conn);
                return Json(new { code = 1, msg = "删除成功" });
            }
        }
        public ActionResult LogDeleteAll()
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.LogConn))
            {
                conn.Open();
                logDal.DeleteAll(conn);
                return Json(new { code = 1, msg = "删除成功" });
            }
        }
    }
}

Dyd.BusinessMQ.Web/Areas/Manage/Controllers/ConfigController.cs
using Dyd.BusinessMQ.Core;
using Dyd.BusinessMQ.Domain;
using Dyd.BusinessMQ.Domain.Model;
using Dyd.BusinessMQ.Web.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XXF.Db;

namespace Dyd.BusinessMQ.Web.Areas.Manage.Controllers
{
    public class ConfigController : BaseController
    {
        private Dyd.BusinessMQ.Domain.Dal.tb_config_dal configDal = new Dyd.BusinessMQ.Domain.Dal.tb_config_dal();
        // GET: /Manage/Config/

        public ActionResult Index()
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                IList<tb_config_model> list = configDal.GetList(conn);
                return View(list);
            }
        }
        /// <summary>
        /// Delete
        /// </summary>
        /// <param name="key"></param>
        /// <returns></returns>
        public ActionResult Delete(string key)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                bool flag = configDal.Delete(conn, key);
                if (flag)
                {
                    CacheManage.Remove("configCache");
                    return Json(new { code = 1, msg = "删除成功" });
                }
                return Json(new { code = -1, msg = "删除失败" });
            }
        }
        [HttpPost]
        public ActionResult Update(tb_config_model model)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                bool flag = configDal.Edit(conn, model);
                if (flag)
                {
                    CacheManage.Remove("configCache");
                    return RedirectToAction("index");
                }
                else
                {
                    ModelState.AddModelError("Error", "更新错误");
                    return View(model);
                }
            }
        }
        public ActionResult Update(string key)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                tb_config_model model = configDal.Get(conn, key);
                return View(model);
            }
        }
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(tb_config_model model)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                bool flag = configDal.Add(conn, model);
                if (flag)
                {
                    CacheManage.Remove("configCache");
                    return RedirectToAction("index");
                }
                else
                {
                    ModelState.AddModelError("Error", "更新错误");
                    return View(model);
                }
            }
        }
    }
}

Dyd.BusinessMQ.Web/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/css/css.css" rel="stylesheet" />
    <link href="~/Content/HighChartPackCss.css" rel="stylesheet" />
@*        <link href="~/Content/themes/base/jquery.ui.all.css" rel="stylesheet" />*@
        <script src="~/Scripts/jquery-1.8.2.min.js" type="text/javascript"></script>
@*    <script src="~/Scripts/jquery-ui-1.8.20.min.js"></script>*@

    <script src="~/Scripts/DatePicker/WdatePicker.js"></script>
    <script src="~/Content/js/common.js"></script>
    @RenderSection("Styles", false)
    @RenderSection("Scripts", false)
</head>
<body>
     <div class="header">
        <span style="color: white; font-size: 25px; margin-left: 25px; font-weight: bold; font-family: 微软雅黑;">点呀点业务消息平台</span>
        <div class="fr mr10">
            
            <span id="toptips" class="remind fl"><span id="toptips1"></span></span>
            @if (User.Identity.IsAuthenticated)
            {
                <a href="/login/logout" class="fl">退出</a>
            }
            else
            {
                <a href="/login/login" class="fl">登录</a>
            }
        </div>
    </div>
    <div class="content w">
        <div class="leftmenu fl">
            <ul class="level1">
        
                <li>
                    <p>队列管理<i></i></p>
                    <ul class="level2">
                        <li><a href="@Url.Action("Index", "Queue", new { area="ProConsum" })">队列管理</a></li>
                    </ul>
                    <ul class="level2">
                        <li><a href="@Url.Action("Index", "Product", new { area="ProConsum" })">生产者管理</a></li>
                    </ul>
                    <ul class="level2">
                        <li><a href="@Url.Action("Index", "Consumer", new { area="ProConsum" })">消费者管理</a></li>
                    </ul>
                </li>
                <li>
                    <p>分区管理<i></i></p>
                     <ul class="level2">
                        <li><a href="@Url.Action("Index", "QueuePartition", new { area="DataNode" })">队列分区管理</a></li>
                    </ul>
                    <ul class="level2">
                        <li><a href="@Url.Action("Index", "Node", new { area="DataNode" })">数据节点管理</a></li>
                    </ul>
                    <ul class="level2">
                        <li><a href="@Url.Action("Index", "Partition", new { area="DataNode" })">表分区管理</a></li>
                    </ul>
                </li>
                  <li>
                    <p>消息管理<i></i></p>
                    <ul class="level2">
                        <li><a href="@Url.Action("Index", "Message", new { area="Message" })">消息管理</a></li>
                    </ul>
                </li>
                 <li>
                    <p>配置管理<i></i></p>
                    <ul class="level2">
                        <li><a href="@Url.Action("Index", "Config", new { area="Manage" })">参数配置</a></li>
                    </ul>
                </li>
                  <li>
                    <p>日志查看<i></i></p>
                      <ul class="level2">
                        <li><a href="@Url.Action("ErrorIndex", "Log", new { area="Log" })">错误日志</a></li>
                    </ul>
                    <ul class="level2">
                        <li><a href="@Url.Action("LogIndex", "Log", new { area="Log" })">常用日志</a></li>
                    </ul>
                         <ul class="level2">
                        <li><a href="@Url.Action("DebugIndex", "Log", new { area="Log" })">调试日志</a></li>
                    </ul>
                         
                </li>
            </ul>
        </div>
        <div class="main_cont">
            @RenderBody()
        </div>
    </div>
</body>
</html>