Dyd.BusinessMQ.Web/Areas/ProConsum/Controllers/ConsumerController.cs
using Dyd.BusinessMQ.Domain;
using Dyd.BusinessMQ.Domain.Dal;
using Dyd.BusinessMQ.Domain.Model.manage;
using Dyd.BusinessMQ.Web.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XXF.Db;
using Dyd.BusinessMQ.Domain.Model;
using Webdiyer.WebControls.Mvc;

namespace Dyd.BusinessMQ.Web.Areas.ProConsum.Controllers
{
    public class ConsumerController : BaseController
    {
        //
        // GET: /ProConsum/Consumer/

        private tb_consumer_dal dal = new tb_consumer_dal();
        public ActionResult Index(string partitionid, string consumerclientid, string mqpathid, int pageIndex = 1, int pageSize = 30)
        {
            ViewBag.partitionid = partitionid; ViewBag.consumerclientid = consumerclientid; ViewBag.mqpathid = mqpathid;
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                ViewBag.ServerDate = conn.GetServerDate();
                int count = 0;
                var list = dal.GetPageList2(conn, partitionid, consumerclientid, mqpathid, pageIndex, pageSize, ref count);
                PagedList<RegisterdConsumersModel> pageList = new PagedList<RegisterdConsumersModel>(list, pageIndex, pageSize, count);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("List", pageList);
                }

                return View(pageList);
            }
        }
        [HttpPost]
        public ActionResult Delete(int id, int mqpathid)
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
                {
                    try
                    {
                        conn.Open();
                        conn.BeginTransaction();

                        var item = new tb_consumer_partition_dal().Get(conn, id);
                        new tb_consumer_dal().DeleteNotOnLineByClientID(conn, item.consumerclientid, 20);
                        var consumer = new tb_consumer_dal().GetByTempId(conn, item.lastconsumertempid);
                        if (consumer != null && consumer.tempid == 0)
                        {
                            throw new Exception("当前消费者未处于正常离线状态,若是非正常断线状态,可以在20s超时后尝试");
                        }
                        new tb_consumer_partition_dal().Delete(conn, id);
                        conn.Commit();

                    }
                    catch (Exception exp)
                    {
                        conn.Rollback();
                        throw exp;
                    }
                }
                this.SendCommandToRedistReStart(mqpathid, XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.EnumCommandReceiver.Consumer);
                return Json(new { code = 1, msg = "删除成功" });
            }

            catch (Exception e)
            {
                return Json(new { code = -1, msg = e.Message });
            }

        }
        [HttpPost]
        public ActionResult ClearNotOnLineByClientID(int id, int mqpathid)
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
                {
                    try
                    {
                        conn.Open();
                        conn.BeginTransaction();
                        var item = new tb_consumer_partition_dal().Get(conn, id);
                        new tb_consumer_dal().DeleteNotOnLineByClientID(conn, item.consumerclientid, 20);

                        conn.Commit();

                    }
                    catch (Exception exp)
                    {
                        conn.Rollback();
                        throw exp;
                    }

                    return Json(new { code = 1, msg = "清理完毕" });
                }
            }
            catch (Exception e)
            {
                return Json(new { code = -1, msg = e.Message });
            }

        }
        public ActionResult UpdateLastMqID(int id, string mqpathid)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                var o = new tb_consumer_partition_dal().Get(conn, id);
                ViewBag.id = id;
                ViewBag.lastmqid = o.lastmqid; ViewBag.mqpathid = mqpathid;

            }
            return View();

        }
        [HttpPost]
        public ActionResult SaveUpdateLastMqID(int id, long lastmqid, int mqpathid)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                try
                {
                    if (new tb_consumer_partition_dal().UpdateLastMqIdByPartitionId(conn, id, lastmqid) > 0)
                    {
                        this.SendCommandToRedistReStart(mqpathid, XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.EnumCommandReceiver.Consumer);
                        return RedirectToAction("index");
                    }
                    else
                    {
                        ModelState.AddModelError("Error", "更新失败");
                        return View();
                    }
                }
                catch (Exception exp)
                {
                    ModelState.AddModelError("Error", exp.Message);
                    return View();
                }
            }
        }
    }
}

Dyd.BusinessMQ.Web/Areas/ProConsum/Controllers/ProductController.cs
using Dyd.BusinessMQ.Domain;
using Dyd.BusinessMQ.Domain.Dal;
using Dyd.BusinessMQ.Domain.Model;
using Dyd.BusinessMQ.Web.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using XXF.Db;
using Dyd.BusinessMQ.Domain.Model.manage;
using Webdiyer.WebControls.Mvc;

namespace Dyd.BusinessMQ.Web.Areas.ProConsum.Controllers
{
    public class ProductController : BaseController
    {
        private tb_producter_dal dal = new tb_producter_dal();
        //
        // GET: /ProConsum/Product/

        public ActionResult Index(string mqpathid,string name, string ip, int pageIndex = 1, int pageSize = 30)
        {
            ViewBag.mqpathid = mqpathid;
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open(); ViewBag.ServerDate = conn.GetServerDate();
                int count = 0;
                IList<tb_producterview_model> list = dal.GetPageList(conn,mqpathid, name, ip, pageIndex, pageSize, ref count);
                PagedList<tb_producterview_model> pageList = new PagedList<tb_producterview_model>(list, pageIndex, pageSize, count);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("List", pageList);
                }
                ViewBag.ServerDate = conn.GetServerDate();
                return View(pageList);
            }
        }
        public ActionResult Update(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                tb_producter_model model = dal.Get(conn, id);
                return View(model);
            }
        }
        [HttpPost]
        public ActionResult Update(tb_producter_model model)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                tb_producter_model result = dal.Get(conn, model.id);
                if (result != null)
                {
                    result.mqpathid = model.mqpathid;
                    result.productername = model.productername;
                    result.ip = model.ip;
                    if (dal.Edit(conn,result))
                    {
                        return RedirectToAction("index");
                    }
                }
                ModelState.AddModelError("Error", "更新错误");
                return View(result);
            }
        }
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                bool flag = dal.Delete(conn, id); 
                if (flag)
                {
                    return Json(new { code = 1, msg = "删除成功" });
                }
                else
                {
                    return Json(new { code = -1, msg = "删除失败" });
                }
            }
        }

        [HttpPost]
        public ActionResult DeleteOffLine()
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
                {
                    conn.Open();
                    bool flag = dal.DeleteOffLine(conn, XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.SystemParamConfig.Producter_Heartbeat_MAX_TIME_OUT);
                   
                }
                return Json(new { code = 1, msg = "离线清理成功" });
            }
            catch (Exception exp)
            {
                return Json(new { code = -1, msg = exp.Message});
            }
        }
    }
}

Dyd.BusinessMQ.Web/Areas/ProConsum/Controllers/QueueController.cs
using Dyd.BusinessMQ.Domain;
using Dyd.BusinessMQ.Domain.Dal;
using Dyd.BusinessMQ.Domain.Model;
using Dyd.BusinessMQ.Domain.Model.manage;
using Dyd.BusinessMQ.Web.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime;
using XXF.Db;
using Webdiyer.WebControls.Mvc;
using XXF.Extensions;

namespace Dyd.BusinessMQ.Web.Areas.ProConsum.Controllers
{
    public class QueueController : BaseController
    {
        //
        // GET: /DataNode/Queue/

        private tb_mqpath_partition_dal dal = new tb_mqpath_partition_dal();
        private tb_mqpath_dal pathDal = new tb_mqpath_dal();

        public ActionResult Index(string mqpathid = "", string mqpath = "", int pageIndex = 1, int pageSize = 30, int partitionId = 0)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                int count = 0;
                ViewBag.mqpathid = mqpathid; ViewBag.mqpath = mqpath;
                ViewBag.partitionId = partitionId;
                ViewBag.ServerDate = conn.GetServerDate();
                IList<MqPathModel> list = pathDal.GetPageList(conn, mqpathid, mqpath, pageIndex, pageSize, ref count);
                PagedList<MqPathModel> pageList = new PagedList<MqPathModel>(list, pageIndex, pageSize, count);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("List", pageList);
                }
                return View(pageList);
            }
        }
        public ActionResult Update(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                tb_mqpath_model model = pathDal.Get(conn, id);
                return View(model);
            }
        }
        [HttpPost]
        public ActionResult Update(tb_mqpath_model model)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                tb_mqpath_model result = pathDal.Get(conn, model.id);
                if (result != null)
                {
                    result.mqpath = model.mqpath;
                    result.lastupdatetime = DateTime.Now;
                    if (pathDal.Edit(conn, result))
                    {
                        return RedirectToAction("index");
                    }
                }
                ModelState.AddModelError("Error", "更新错误");
                return View(result);
            }
        }
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(string mqpath)
        {
            try
            {
                if (mqpath.isint() == true)
                    throw new Exception("队列名不允许为数字");
                using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
                {
                    conn.Open();
                    if (pathDal.Add2(conn, mqpath.ToLower()))
                    {
                        return RedirectToAction("index");
                    }
                    throw new Exception("添加错误");
                }
            }
            catch (Exception exp)
            {
                ModelState.AddModelError("Error", exp.Message);
                return View(mqpath);
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
                {
                    try
                    {
                        conn.Open();
                        conn.BeginTransaction();
                        var countofpatitions = dal.GetCountOfPartition(conn, id);
                        if (countofpatitions > 0)
                            throw new Exception("请先删除该队列全部分区后删除该队列");
                        new tb_mqpath_dal().Delete(conn, id);
                        conn.Commit();
                        return Json(new { code = 1, msg = "删除成功" });
                    }
                    catch (Exception exp)
                    {
                        conn.Rollback();
                        throw exp;
                    }

                }
            }
            catch (Exception exp)
            {

                return Json(new { code = -1, msg = exp.Message });
            }
        }



        public ActionResult ReStart(int id)
        {
            try
            {
                ReStartQuque(id);
                return Json(new { code = 1, msg = "已通知消费者和生产者更新" });

            }
            catch (Exception exp)
            {

                return Json(new { code = -1, msg = exp.Message });
            }
        }
    }
}

Dyd.BusinessMQ.Web/Areas/ProConsum/Views/Queue/Add.cshtml
@{
    ViewBag.Title = "新增";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    function sub() {
        if ($("#id").val() == "") {
            alert("请填写id")
            return false;
        }
        if ($("#mqpath").val() == "") {
            alert("请填写名称");
            return false;
        }
    }
</script>
<div class="head">
    <div class="title">
       新增队列
    </div>
</div>
<div>
    @using (Html.BeginForm("Add", "Queue", FormMethod.Post, new { enctype = "multipart/form-data", @onsubmit = "return sub()" }))
    {
    <ul class="mydetail">
       @* <li>
            <label>队列编号</label><input  type="text" id="id" name="id" />
        </li>*@
        <li> 
            <label>名称</label><input type="text" id="mqpath" name="mqpath" />（格式:类似类的命名空间方式,如dyd.capi.order.add,能够表达业务的方式，不允许使用数字等无意义的命名方式。）
        </li>
        <li>
            <input type="submit" class="btn1" value="提交" />@Html.ValidationMessage("Error")
        </li>
    </ul>
    }
</div>

Dyd.BusinessMQ.Web/Areas/ProConsum/Views/Queue/Index.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BusinessMQ.Domain.Model.manage.MqPathModel>
@{
    ViewBag.Title = "队列管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    function Delete(id) {
        if (confirm("确定删除吗？")) {
            $.ajax({
                url: '@Url.Action("Delete","Queue")',
                type: "post",
                data: {
                    id: id
                },
                success: function (data) {
                    if (data.code > 0) {
                        alert("成功！");
                        window.location = window.location;
                    }
                    else {
                        alert(data.msg);
                    }
                }
            })
        }
    }

    function ReStart(id) {
        if (confirm("确定通知客户端和生产者端自动重启吗？")) {
            $.ajax({
                url: '@Url.Action("ReStart","Queue")',
                type: "post",
                data: {
                    id: id
                },
                success: function (data) {
                    if (data.code > 0) {
                        alert("成功！");
                        window.location = window.location;
                    }
                    else {
                        alert(data.msg);
                    }
                }
            })
        }
    }
</script>
@section Scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    @{Html.RegisterMvcPagerScriptResource();}
}
<div class="head">
    <div class="title">
        队列管理 @Html.Raw(Dyd.BusinessMQ.Web.Base.CommonHelper.Help(@"队列的管理,用于队列的新建和删除等操作;注意：删除队列,请先确定队列的消费者和生产者都已经被删除,队列无关联分区。重启操作表示通知相关的生产者和消费者自动重启,队列可能导致极少部分消息重新消费,不建议线上频繁执行"))
    </div>
</div>
<div class="orderlist m10 myorder">
    @using (Html.BeginForm("index", "Queue", FormMethod.Get, new RouteValueDictionary { { "id", "searchForm" } }))
    {
        <div class="item_list pt10">
            <div class="item_list">
                <ul>
                    <li>
                        <label>ID</label>
                        <input type="text" style="width:150px" name="mqpathid" value="@ViewBag.mqpathid" />
                        <label>队列名</label>
                        <input type="text" style="width:200px" name="mqpath" value="@ViewBag.mqpath" />
                    </li>
                   @* <li>
                        <label>创建时间</label><input type="text" class="text" autocomplete="off"name="CStime" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss',minDate:'1900-01-01',readOnly:true})" value="@(string.IsNullOrEmpty(ViewBag.CStime)?"":ViewBag.CStime)" />
                        至
                    <input type="text" class="text" autocomplete="off" name="CEtime" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss',minDate:'1900-01-01',readOnly:true})" value="@(string.IsNullOrEmpty(ViewBag.CEtime)?"":ViewBag.CEtime)"/>
                    </li>*@
                    <li class="search">
                        <input type="submit" class="btn1" value="搜索" accesskey="S" /></li>
                </ul>
            </div>
        </div>
    }
    <a href="@Url.Action("add", "Queue")" class="btn1">新增</a>
    <div class="tab_cont">
        <div class="List">
            @Html.Partial("List",Model)
        </div>
    </div>
</div>

Dyd.BusinessMQ.Web/Areas/ProConsum/Views/Queue/List.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BusinessMQ.Domain.Model.manage.MqPathModel>

<style>


        .divhide {
        overflow:hidden;
        height:200px;
        }
    .divopen {
    }
</style>
<table>
    <tbody><tr>
        <th style="width:200px;">队列</th>
        <th style="width:300px;">分区信息</th>
        <th>操作</th>
    </tr>
        @foreach (var item in Model)
        {
               <tr style=" ">
            <td style="text-align:left; vertical-align:top;">
                【ID】@item.id<br>
                【名称】@item.mqpath<br>
                【更新】@Dyd.BusinessMQ.Core.CommonHelper.ShowTime(ViewBag.ServerDate,item.lastupdatetime)<br>
                【创建】@Dyd.BusinessMQ.Core.CommonHelper.ShowTime(ViewBag.ServerDate,item.createtime)<br>
            </td>
            <td style="text-align:left; vertical-align:top;"> 
              <a target="_blank" href="@Url.Action("Index", "Consumer", new { Area="ProConsum",mqpathid=item.id })">【消费者】<span>@item.Connsumer [注册]</span>&nbsp;&nbsp;<span>@item.NonConnsumer [离线]</span></a>
              <br>
              <a target="_blank" href="@Url.Action("Index", "Product", new { Area="ProConsum",mqpathid=item.id })">【生产者】<span>@item.ProductCount [在线]</span>&nbsp;&nbsp;<span>@item.NonProductCount [离线]</span></a>
             <br>
              <a target="_blank" href="@Url.Action("Index", "QueuePartition", new { Area="DataNode",mqpathid=item.id })">【表分区】<span>@item.Partition [活动]</span>&nbsp;&nbsp;<span>@item.NonPartition [待删]</span></a>
            </td>
            <td>
               @* <a href="/DataNode/Queue/Update/@item.id">修改</a>*@
                @if (item.Partition <= 0 && @item.NonPartition <= 0 && item.Connsumer <= 0 && item.NonConnsumer <= 0 && item.ProductCount <= 0 && item.NonProductCount <= 0)
                {<input type="button" value="删除" onclick="Delete('@item.id')">}
                
                <input title="重启相关消费者和生产者,可能会导致部分消息重复执行,不建议频繁操作" type="button" value="重启" onclick="ReStart('@item.id    ')">
            </td>
        </tr>
        }
</tbody></table>
<div class="total pt10">
    <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
    @Html.Pager(Model,new PagerOptions{PageIndexParameterName = "pageindex",ShowPageIndexBox = true,PageIndexBoxType = PageIndexBoxType.TextBox, CssClass="mvcPager"})
    @*@Ajax.Pager(Model, new PagerOptions { PageIndexParameterName = "pageindex", ShowPageIndexBox = true, PageIndexBoxType = PageIndexBoxType.DropDownList, ShowGoButton = false }, new MvcAjaxOptions { UpdateTargetId = "List", HttpMethod = "Post", DataFormId = "searchForm" }, new { @class = "pager_page" })*@
</div>

Dyd.BusinessMQ.Web/Areas/ProConsum/Views/Queue/Update.cshtml
@model Dyd.BusinessMQ.Domain.Model.tb_mqpath_model
@{
    ViewBag.Title = "修改";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    function sub() {
        if ($("#mqpath").val() == "") {
            alert("请填写名称");
            return false;
        }
    }
</script>
<div class="head">
    <div class="title">
       修改队列
    </div>
</div>
<div>
    @using (Html.BeginForm("Add", "Queue", FormMethod.Post, new { enctype = "multipart/form-data", @onsubmit = "return sub()" }))
    {
    <ul class="mydetail">
      <input  type="hidden" id="id" name="id"  value="@Model.id" />
        <li> 
            <label>名称</label><input type="text" id="mqpath" name="mqpath" value="@Model.mqpath" />
        </li>
        <li>
            <input type="submit" class="btn1" value="提交" />@Html.ValidationMessage("Error")
        </li>
    </ul>
    }
</div>