Dyd.BusinessMQ.Web/Areas/DataNode/Controllers/NodeController.cs
using Dyd.BusinessMQ.Domain;
using Dyd.BusinessMQ.Domain.Dal;
using Dyd.BusinessMQ.Domain.Model;
using Dyd.BusinessMQ.Web.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XXF.Db;
using Webdiyer.WebControls.Mvc;

namespace Dyd.BusinessMQ.Web.Areas.DataNode.Controllers
{
    public class NodeController : BaseController
    {
        private tb_datanode_dal nodeDal = new tb_datanode_dal();
        private tb_partition_dal partitionDal = new tb_partition_dal();
        private int pageSize = 30;
        //
        // GET: /DataNode/Node/

        public ActionResult Index(int pageIndex = 1)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                int count = 0;
                IList<tb_datanode_model> list = nodeDal.GetPageList(conn, pageIndex, pageSize, ref count);
                PagedList<tb_datanode_model> pageList = new PagedList<tb_datanode_model>(list, pageIndex, pageSize, count);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("List", pageList);
                }
               
                return View(pageList);
            }
        }
        public ActionResult Delete(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                var model = new tb_datanode_dal().Get(conn,id);
                bool isExistPartion = partitionDal.IsExistPartition(conn, model.datanodepartition);
                if (isExistPartion)
                {
                    return Json(new { code = -1, msg = "该节点存在分区，请先删除分区，再进行删除节点操作" });
                }
                else
                {
                    bool flag = nodeDal.Delete(conn, id);
                    if (flag)
                    {
                        return Json(new { code = 1, msg = "删除成功" });
                    }
                    return Json(new { code = -1, msg = "删除失败" });
                }
            }
        }
        [HttpPost]
        public ActionResult Update(tb_datanode_model model)
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
                {
                    conn.Open();
                    if (model.datanodepartition < 1 || model.datanodepartition >= 100)
                    {
                        throw new Exception("节点编号只允许1~99之间");
                    }
                    if (nodeDal.IsExist(conn, model.id, model.datanodepartition))
                    {
                        throw new Exception("节点编号已存在");
                    }
                    if (nodeDal.Edit(conn, model) == false)
                    {
                        throw new Exception("更新错误");
                    }
                }
                return RedirectToAction("index");
            }
            catch (Exception exp)
            {
                ModelState.AddModelError("Error", exp.Message);
                return View(model);
            }
        }
        public ActionResult Update(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                tb_datanode_model model = nodeDal.Get(conn, id);
                return View(model);
            }
        }
        public ActionResult Add()
        {
            IList<string> usednodes = new List<string>();
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                usednodes = new tb_datanode_dal().GetNodeList(conn);
            }
            List<string> unUsednodes = new List<string>();
            for (var i = 1; i < 100; i++)
            {
                var nodeid = XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.PartitionRuleHelper.PartitionNameRule(i);
                //var partition = XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.PartitionRuleHelper.GetPartitionID(new XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.PartitionIDInfo() { DataNodePartition = nodeid, TablePartition = i });
                if (!usednodes.Contains(nodeid))
                    unUsednodes.Add(nodeid);
            }
            ViewBag.unusednodes = unUsednodes;
            return View();
        }
        [HttpPost]
        public ActionResult Add(tb_datanode_model model)
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
                {
                    conn.Open();
                    if (model.datanodepartition < 1 || model.datanodepartition >= 100)
                    {
                        throw new Exception("节点编号只允许1~99之间");
                    }
                    if (nodeDal.IsExist(conn, model.id, model.datanodepartition))
                    {
                        throw new Exception("节点编号已存在");
                    }
                    if (nodeDal.Add(conn, model) == false)
                    {
                        throw new Exception("更新错误");
                    }
                }
                return RedirectToAction("index");
            }
            catch (Exception exp)
            {
                ModelState.AddModelError("Error", exp.Message);
                return View(model);
            }
        }
    }
}

Dyd.BusinessMQ.Web/Areas/DataNode/Controllers/PartitionController.cs
using Dyd.BusinessMQ.Domain;
using Dyd.BusinessMQ.Domain.Dal;
using Dyd.BusinessMQ.Domain.Model;
using Dyd.BusinessMQ.Web.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XXF.Db;
using Webdiyer.WebControls.Mvc;

namespace Dyd.BusinessMQ.Web.Areas.DataNode.Controllers
{
    public class PartitionController : BaseController
    {
        private tb_partition_dal dal = new tb_partition_dal();
        //
        // GET: /DataNode/Partition/

        public ActionResult Index(string partitionid,string nodeId,int used=-1, int pageIndex = 1, int pageSize = 30)
        {
            ViewBag.nodeId = nodeId; ViewBag.used = used; ViewBag.partitionid = partitionid;
            int nnodeid =( string.IsNullOrWhiteSpace(nodeId)?0: Convert.ToInt32(nodeId));
            
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open(); ViewBag.ServerDate = conn.GetServerDate();
                int count = 0;
                IList<tb_partition_model> list = dal.GetPageList(conn,partitionid, nnodeid,used, pageIndex, pageSize, ref count);
                PagedList<tb_partition_model> pageList = new PagedList<tb_partition_model>(list, pageIndex, pageSize, count);
                ViewBag.Nodes = new tb_datanode_dal().GetNodeList(conn);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("List", pageList);
                }
                return View(pageList);
            }
        }
        public ActionResult Delete(int partitionId)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                int result = dal.DeletePartition(conn, partitionId);
                switch (result)
                {
                    case 0:
                        return Json(new { code = -1, msg = "分区正在使用，无法删除，请先删除该分区下的队列" });
                    case 1:
                        return Json(new { code = 1, msg = "删除成功" });
                    case -1:
                        return Json(new { code = -1, msg = "数据不存在" });
                    case -2:
                        return Json(new { code = -1, msg = "删除失败" });
                    default:
                        return Json(new { code = -1, msg = "未知错误" });
                }
            }
        }
        public ActionResult Add(int nodeId=0)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                ViewBag.nodeId = nodeId;
                int count=0;
                ViewBag.datanodes = new tb_datanode_dal().GetPageList(conn, 1, 100, ref count);
            }
            return View();
        }
        public ActionResult PartitionsCount(int nodeId)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                int count = 0;
                new tb_partition_dal().GetPageList(conn,"",nodeId,-1, 1, 100, ref count);
                return Json(new { code = 1, count = count });
            }
        }
        [HttpPost]
        public ActionResult Add(int nodeid,int count)
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.MqManage))
                {
                    conn.Open();
                    try
                    {
                        conn.BeginTransaction();
                        int r = 0;
                        var partitons = new tb_partition_dal().GetPageList(conn, "", nodeid, -1, 1, 100, ref r);
                        List<int> usedpartitionids = new List<int>();
                        foreach (var d in partitons)
                        {
                            if (!usedpartitionids.Contains(d.partitionid))
                                usedpartitionids.Add(d.partitionid);
                        }
                        List<int> canusepartitionids = new List<int>();
                        for (var i = 1; i < 100; i++)
                        {
                            var partition = XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.PartitionRuleHelper.GetPartitionID(new XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.PartitionIDInfo() { DataNodePartition = nodeid, TablePartition =i  });
                            if (!usedpartitionids.Contains(partition))
                                canusepartitionids.Add(partition);
                        }
                        for (int i = 0; i < count; i++)
                        {
                            tb_partition_model model = new tb_partition_model();
                            model.isused = false;
                            model.partitionid = canusepartitionids[i];
                            dal.AddPartition(conn, model);
                        }
                        conn.Commit();
                    }
                    catch (Exception exp)
                    {
                        conn.Rollback();
                        throw exp;
                    }
                }
                return RedirectToAction("index", new { nodeId = nodeid });
            }
            catch (Exception exp)
            {
                ModelState.AddModelError("Error","添加失败"+ exp.Message);
                return View();
            }
           
        }
    }
}

Dyd.BusinessMQ.Web/Areas/DataNode/Views/Node/Add.cshtml
@{
    ViewBag.Title = "新增";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    function sub() {
        if ($("#datanodepartition").val() == "") {
            alert("请填写节点")
            return false;
        }
        if ($("#serverip").val() == "") {
            alert("请填写ip");
            return false;
        }
        if ($("#username").val() == "") {
            alert("请填写用户名");
            return false;
        }
        if ($("#password").val() == "") {
            alert("请填写密码");
            return false;
        }
    }
</script>
<div class="head">
    <div class="title">
        新增节点 @Html.Raw(Dyd.BusinessMQ.Web.Base.CommonHelper.Help(@"先用数据库中增加数据节点库后,再在管理平台中增加!"))
    </div>
</div>
<div>
    @using (Html.BeginForm("Add", "Node", FormMethod.Post, new { enctype = "multipart/form-data", @onsubmit = "return sub()" }))
    {
    <ul class="mydetail">
        <li>
            <label>节点编号</label>@*<input  type="text" id="datanodepartition" name="datanodepartition" />（不可重复 01~99之间）*@
            <select id="datanodepartition" name="datanodepartition">
                @foreach (var o in ViewBag.unusednodes)
                {
                   <option value="@o">@o</option> 
                }
            </select>
        </li>
        <li> 
            <label>IP</label><input type="text" id="serverip" name="serverip" />
        </li>
        <li>
            <label>用户名</label><input type="text" id="username" name="username" />
        </li>
         <li>
            <label>密码</label><input type="text" id="password" name="password" />
        </li>
        <li>
            <input type="submit" class="btn1" value="提交" />@Html.ValidationMessage("Error")
        </li>
    </ul>
    }
</div>

Dyd.BusinessMQ.Web/Areas/DataNode/Views/Node/Index.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BusinessMQ.Domain.Model.tb_datanode_model>
@{
    ViewBag.Title = "数据节点管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    @{Html.RegisterMvcPagerScriptResource();}
}
<script>
    function Delete(id) {
        if (confirm("确定删除吗？")) {
            $.ajax({
                url: '@Url.Action("Delete", "Node")',
                type: "post",
                data: {
                    id: id
                },
                success: function (data) {
                    if (data.code > 0) {
                        alert("成功！");
                        window.location = window.location;
                    }
                    else {
                        alert(data.msg);
                    }
                }
            })
        }
    }
</script>
<div class="head">
    <div class="title">
        数据节点管理 @Html.Raw(Dyd.BusinessMQ.Web.Base.CommonHelper.Help(@"数据库节点的管理,注意:新增和修改的数据库节点,需要重启相应的队列方可生效;删除管理节点,需先删除管理节点下面的所有分区。"))
    </div>
</div>
<div class="orderlist m10 myorder">
    <a href="@Url.Action("Add", "Node")" class="btn1">新增</a>
   <div class="List">
            @Html.Partial("List",Model)
        </div>
</div>

Dyd.BusinessMQ.Web/Areas/DataNode/Views/Node/List.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BusinessMQ.Domain.Model.tb_datanode_model>      

 <table>
    <tr>
@*        <th>id</th>*@
        <th>分区编号</th>
        <th>IP</th>
        <th>用户名</th>
        <th>密码</th>
        <th>操作</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
@*            <td>@item.id</td>*@
            <td>@XXF.BaseService.MessageQuque.BusinessMQ.SystemRuntime.PartitionRuleHelper.PartitionNameRule(item.datanodepartition)</td>
            <td>@item.serverip</td>
            <td>
               @item.username
            </td>
            <td>***********</td>
            <td>
                 <a href="@Url.Action("Update", "Node", new { id = @item.id })">修改</a>
                <a target="_blank" href="@Url.Action("Index", "Partition", new { nodeId=@item.datanodepartition})">相关表分区</a>
                <input type="button" value="删除" onclick="Delete('@item.id')" />
            </td>
        </tr>
    }
</table>
<div class="total pt10">
    <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
    @Html.Pager(Model,new PagerOptions{PageIndexParameterName = "pageIndex",ShowPageIndexBox = true,PageIndexBoxType = PageIndexBoxType.TextBox, CssClass="mvcPager"})
</div>

Dyd.BusinessMQ.Web/Areas/DataNode/Views/Node/Update.cshtml
@{
    ViewBag.Title = "新增";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Dyd.BusinessMQ.Domain.Model.tb_datanode_model
<script>
    function sub() {
        if ($("#datanodepartition").val() == "") {
            alert("请填写节点")
            return false;
        }
        if ($("#serverip").val() == "") {
            alert("请填写ip");
            return false;
        }
        if ($("#username").val() == "") {
            alert("请填写用户名");
            return false;
        }
        if ($("#password").val() == "") {
            alert("请填写密码");
            return false;
        }
    }
</script>
<div class="head">
    <div class="title">
        新增节点
    </div>
</div>
<div>
    @using (Html.BeginForm("Update", "Node", FormMethod.Post, new { enctype = "multipart/form-data", @onsubmit = "return sub()" }))
    {
    <ul class="mydetail">
        <input name="id" value="@Model.id" type="hidden"/>
        <li>
            <label>节点编号</label><input  type="text" id="datanodepartition" name="datanodepartition" readonly="readonly" value="@Model.datanodepartition" />（不可重复 01~99之间）
        </li>
        <li>
            <label>IP</label><input type="text" id="serverip" name="serverip" value="@Model.serverip" />
        </li>
        <li>
            <label>用户名</label><input type="text" id="username" name="username" value="@Model.username" />
        </li>
         <li>
            <label>密码</label><input type="text" id="password" name="password" value="@Model.password" />
        </li>
        <li>
            <input type="submit" class="btn1" value="提交" />@Html.ValidationMessage("Error")
        </li>
    </ul>
    }
</div>